const express = require("express");
const cors = require("cors");
const cookieParser = require("cookie-parser");
const loginRoute = require("./router/LoginRoute");
const app = express();
app.use(cookieParser());
app.use(express.json());
app.use(cors({ Credential: true, origin: "http://localhost:3000" }));
app.use(loginRoute);
app.listen(5000);
